import { Link } from "@tanstack/react-router";
import { useState, type ReactNode } from "react";

const tools = [
  { to: "/", label: "Dashboard", icon: "✦" },
  { to: "/email", label: "Email Generator", icon: "✉️" },
  { to: "/notes", label: "Notes Summarizer", icon: "📝" },
  { to: "/planner", label: "Task Planner", icon: "🗓️" },
  { to: "/research", label: "Research Assistant", icon: "🔎" },
  { to: "/chat", label: "Chat Assistant", icon: "💬" },
] as const;

function NavLinks({ onNavigate }: { onNavigate?: () => void }) {
  return (
    <nav className="px-3 space-y-1 mt-2 text-sm">
      <div className="px-3 py-2.5 font-medium text-muted-foreground text-xs uppercase tracking-wider">
        Workspace
      </div>
      {tools.map((t) => (
        <Link
          key={t.to}
          to={t.to}
          onClick={onNavigate}
          activeOptions={{ exact: t.to === "/" }}
          className="flex items-center gap-3 px-3 py-2.5 rounded-xl font-medium text-foreground/70 hover:bg-secondary"
          activeProps={{
            className:
              "flex items-center gap-3 px-3 py-2.5 rounded-xl font-semibold text-primary-foreground bg-gradient-to-r from-primary to-accent shadow-md shadow-chrome",
          }}
        >
          <span className="text-base">{t.icon}</span> {t.label}
        </Link>
      ))}
    </nav>
  );
}

function CreditsCard() {
  return (
    <div className="mt-auto p-3">
      <div className="rounded-2xl p-3.5 bg-gradient-to-br from-secondary to-card border border-border">
        <p className="font-display font-semibold text-sm">Pro plan</p>
        <p className="text-[11px] text-muted-foreground mt-0.5">820 / 1000 AI credits</p>
        <div className="h-1.5 rounded-full bg-card mt-2.5 overflow-hidden">
          <div className="chrome h-full w-[82%] rounded-full" />
        </div>
      </div>
    </div>
  );
}

export function ResponsibleAiNotice() {
  return (
    <section className="rounded-2xl border border-warning-border bg-warning px-5 py-4 flex items-start gap-3">
      <span className="mt-0.5 text-lg">⚠️</span>
      <p className="text-[13px] text-warning-foreground leading-relaxed">
        <span className="font-semibold">Responsible AI:</span> NovaDesk output is generated by AI and
        may contain errors. Always verify facts, figures, and citations before sending or acting. You
        are responsible for final decisions.
      </p>
    </section>
  );
}

export function AppShell({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="flex">
        <aside className="hidden lg:flex w-64 shrink-0 flex-col border-r border-border bg-card/80 backdrop-blur-sm min-h-screen sticky top-0">
          <div className="px-5 py-5 flex items-center gap-3">
            <div className="chrome size-10 rounded-xl grid place-items-center text-primary-foreground font-display text-lg font-bold shadow-chrome">
              N
            </div>
            <div>
              <p className="font-display font-bold text-[15px] leading-none">NovaDesk</p>
              <p className="text-[11px] text-muted-foreground mt-1">AI Productivity</p>
            </div>
          </div>
          <NavLinks />
          <CreditsCard />
        </aside>

        <main className="flex-1 min-w-0">
          <header className="sticky top-0 z-20 bg-background/85 backdrop-blur-sm border-b border-border">
            <div className="px-4 sm:px-6 lg:px-8 h-16 flex items-center gap-4">
              <button
                onClick={() => setOpen((v) => !v)}
                aria-label="Toggle navigation"
                className="lg:hidden chrome size-9 rounded-lg grid place-items-center text-primary-foreground font-display font-bold"
              >
                N
              </button>
              <div className="hidden sm:flex items-center gap-2 flex-1 max-w-md">
                <div className="flex-1 h-10 rounded-full bg-card border border-border flex items-center px-4 text-sm text-muted-foreground">
                  Search tools, prompts, or docs…
                </div>
              </div>
              <div className="ml-auto flex items-center gap-3">
                <span className="hidden sm:inline-flex items-center gap-1.5 text-xs font-semibold text-success-foreground bg-success border border-border rounded-full px-2.5 py-1">
                  <span className="size-1.5 rounded-full bg-success-foreground" /> Model online
                </span>
                <div className="chrome size-9 rounded-full grid place-items-center text-primary-foreground text-sm font-display font-bold ring-2 ring-card">
                  AR
                </div>
              </div>
            </div>
            {open && (
              <div className="lg:hidden border-t border-border bg-card pb-3">
                <NavLinks onNavigate={() => setOpen(false)} />
              </div>
            )}
          </header>

          <div className="px-4 sm:px-6 lg:px-8 py-6 max-w-6xl mx-auto space-y-6">{children}</div>
        </main>
      </div>
    </div>
  );
}
